name: publish
on: [push]
jobs:
  publish-tinyurl-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write    
    
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build tinyurl-docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          tags: latest
          file: ./Dockerfile
          push: true
